### ISSUE TITLE
sunrgbd数据集的txt文件

### ISSUE THREAD

**Issue by 2295104718** [hmdliu/PAFNet#1]
作者您好，我想请问一下该代码中读取sunrgbd数据集的txt文件是怎么写的。想要一份数据集中的txt文件。

**Comment by hmdliu** [comment]
您好，抱歉回复晚了。SUN-RGBD的metadata可以从[此处](https://drive.google.com/file/d/1ZvTB_VOV0Efxb31qTrEDCET0E_w5DE0p/view?usp=sharing)下载。使用请遵循原数据集的相关许可证。

Hi, sorry for the late reply. You may download SUN-RGBD metadata via [this link](https://drive.google.com/file/d/1ZvTB_VOV0Efxb31qTrEDCET0E_w5DE0p/view?usp=sharing). Please kindly follow all the licenses from the original dataset.
